### ISSUE TITLE
Appearance of the board after each play

### ISSUE THREAD

**Issue by Spiroskarvounis** [realTristan/Checkers#1]
Hello, I would like to report that after executing a move the board is not updated and the programme always shows the board as it was in the beginning.

![BUG](https://user-images.githubusercontent.com/74017491/218345268-e5100c8b-49fe-4748-a998-ebb3f4dd0323.png)

**Comment by realTristan** [comment]
When you enter a move, e.g C-2 > D-3, you're taking the piece from C-2 and moving it to D-3. In checkers, you can only move a piece diagonally by 1 spot. Thus when you type A-2 > B-2, you're moving once forward which doesn't work. Also, 1 is black, 2 is white. I revamped the look of the board and pieces so if you try playing now, everything should look much better.

**Comment by Spiroskarvounis** [comment]
You are right, I misunderstood something. Thank you!
